Updated button icons and added the clearall button/dispatch sequence
thenorthstarblues/Capstone-Project pull request #96
Opened 2017-03-25 14:05 UTC by siteations

does not include full pattern fixes or the final font stuff, fyi.

David- I'd confirm the clear-all is the behavior we want.... it's just setting boxes back to the initial box. Does it need to do anything else to keep the store happy?

2017-03-25 18:26 UTC, thenorthstarblues requested changes

2017-03-25 18:26 UTC, thenorthstarblues commented on src/reducers/boxes.js
> +    case CLEAR_ALL:
have you tested this? might need to be return prevState.clear().mergeWith(initialState)

2017-03-25 18:51 UTC, siteations commented on src/reducers/boxes.js
> +    case CLEAR_ALL:
will write that version and see what the state difference looks like. thanks!

2017-03-25 19:21 UTC, siteations commented
so the store- in redux preview - seems the same either way during testing. It seems better to be consistent with formatting. The other question is whether this resetting to the initial immutable will fuck with the undo/redo, if a user decides they want to undo a clear.

2017-03-25 19:34 UTC, thenorthstarblues commented
Undo probably won't end up working anyway because it will go one step at a time...since we are updating the store every time that they adjust boxes even slightly, it would take the user back each tiny step at a time, so probably not too useful. Does clear all need to be a component? Seems like we could save the code base more clutter by just making it a button

2017-03-25 20:52 UTC, siteations commented
it could be a button if we carve out some space or weed out other div addition options... maybe at the bottom of the fontOptions bar.

2017-03-25 21:10 UTC, siteations commented
which is to say - i'll shift that out tonight when I work on the font bar... carry on.

2017-03-26 17:27 UTC, thenorthstarblues approved these changes

2017-03-26 17:27 UTC, merged